### ISSUE TITLE
SUGGESTION | Lobby items

### ISSUE THREAD

**Issue by 72stom** [2lstudios-mc/SquidGame#14]
```
lobby-items:
  stats:
    name: §dStatistics SquidGame
    lore: §dright click to open
    command: squid stats
    material: BOOK
    data: 0
    enchanted: true
    slot: 0
  play:
    name: §dPlay SquidGame
    lore: §dright click to open
    command: squid join
    material: PAPER
    data: 0
    enchanted: false
    slot: 4
  leave:
    name: §dBack to lobby
    lore: §dright click to back
    command: hub
    material: BED
    data: 0
    enchanted: false
    slot: 7
```
    
when at the lobby location add a gui slot that contains orders so that players feel easy and there are decorations when lobbying
and make sure the lobby items cannot be moved and dropped
