### ISSUE TITLE
SUGGESTION | Spectator Mode

### ISSUE THREAD

**Issue by SofyanTauridOdeMadi** [2lstudios-mc/SquidGame#24]
### Spectator Mode

When the player is in progress, the player can watch the game and can exit

```
spectator-items:
  leave:
    name: §dBack to lobby
    lore: §dright click to back
    command: squid leave
    material: BED
    data: 0
    enchanted: false
    slot: 7
  player:
    name: §dPlayer
    lore: §dright click to view player
    command: squid speed
    material: SKULL
    data: 0
    enchanted: false
    slot: 4
  speed:
    name: §dSpeed
    lore: §dright click to settings speed
    command: squid speed
    material: FEATHER
    data: 0
    enchanted: false
    slot: 1
```
